/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function plus100(input: number): number
export function ensureDir(dir: string): Promise<void>
export function emptyDir(dir: string): Promise<void>
